### listar preguntas

GET http://localhost:3000/pregunta HTTP/1.1

### listar una  preguntas
GET  http://localhost:3000/pregunta/2 HTTP/1.1

### CREAr preguntas
POST  http://localhost:3000/pregunta HTTP/1.1


### eliminar preguntas
DELETE  http://localhost:3000/pregunta/1 HTTP/1.1


### listar personaje

GET http://localhost:3000/personaje HTTP/1.1

### listar una  personaje
GET  http://localhost:3000/personaje/2 HTTP/1.1

### CREAr personaje
POST  http://localhost:3000/personaje HTTP/1.1


### eliminar jugador
DELETE  http://localhost:3000/jugador/1 HTTP/1.1


### listar jugador

GET http://localhost:3000/jugador HTTP/1.1

### listar una  jugador
GET  http://localhost:3000/jugador/1 HTTP/1.1

### CREAr jugador
POST  http://localhost:3000/jugador HTTP/1.1
Content-Type: application/json

{
    "nombre": "mario",
    "descripcui": "sadas",
}

### eliminar jugador
DELETE  http://localhost:3000/jugador/1 HTTP/1.1



### listar preguntaxpersonaje

GET http://localhost:3000/preguntaxjugador HTTP/1.1

### listar una preguntaxpersonaje
GET  http://localhost:3000/preguntaxjugador/pe?id_pregunta=2&respuesta=1 HTTP/1.1

### crear preguntaxpersonaje
POST  http://localhost:3000/preguntaxjugador HTTP/1.1
Content-Type: application/json


{   
  "nombre": "mario",
  "descripcion": " Mario es retratado como un personaje amable, valiente y aventurero. Siempre está dispuesto a ayudar a los demás y se embarca en diversas misiones",
  "foto": "",
  "preguntas": [
    {
      "id_pregunta": 1,
      "respuesta": 0
    },
    {
      "id_pregunta": 2,
      "respuesta": 1
    },
    {
      "id_pregunta": 3,
      "respuesta": 0
    },
    {
      "id_pregunta": 4,
      "respuesta": 0
    },
    {
      "id_pregunta": 5,
      "respuesta": 1
    },
    {
      "id_pregunta": 6,
      "respuesta": 0
    },
    {
      "id_pregunta": 7,
      "respuesta": 0
    },
    {
      "id_pregunta": 8,
      "respuesta": 0
    },
    {
      "id_pregunta": 9,
      "respuesta": 0
    },
    {
      "id_pregunta": 10,
      "respuesta": 0
    },
    {
      "id_pregunta": 11,
      "respuesta": 0
    }
  ]
}