// Generated by https://quicktype.io

export interface Personaje {
  res: import("c:/Users/cr921/Desktop/8 semestre/Sistemas expertos/proyectoCompl/sistemasE/src/app/interfaces/personaje").Re[];
  message: string;
  result: Result[];
}

export interface Result {
  id_personaje: number;
  nombre: string;
  descripcion: string;
  foto: null | string;
}
