// Generated by https://quicktype.io

export interface Onepersonaje {
    message: string;
    res: Re[];
}

export interface Re {
    id_personaje: number;
    nombre: string;
    descripcion: string;
    foto: null;
}
