// Generated by https://quicktype.io

export interface Pregunta {
    message: string;
    resut:   Resut[];
}

export interface Resut {
    id_pregunta: number;
    pregunta:    string;
}
