// Generated by https://quicktype.io

export interface Preguntapersonaje {
    message: string;
    result:  Result[];
}

export interface Result {
    id_pxp:       number;
    id_personaje: number;
    id_pregunta:  number;
    respuesta:    number;
}
